version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb+srv://joke:joke@cluster0.kjd86.gcp.mongodb.net/?retryWrites=true&w=majority

  # mongo_db:
  #   image: mongo:jammy
  #   hostname: mongo_db
  #   container_name: mongo_db
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_DATABASE=test
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   volumes:
  #     # named volumes
  #     - ${PWD}/volume/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - ${PWD}/volume/mongodb:/data/db
  #     - ${PWD}/volume/mongoconfig:/data/configdb
  #   command: mongod

networks:
  my-network: